name: pages-action

on:
  push:
    branches: 
     - main


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Build VitePress
        run: npm run build
      - name: Deploy to Pages
        run: |
          cd docs/.vitepress/dist 
          git init
          git config user.name "${{ secrets.GIT_NAME }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          git commit -m 'deploy'
          git push -f https://${{ secrets.GIT_NAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ secrets.GIT_NAME }}/asmpg.github.io.git main
          cd -
